# Generated by Django 4.1.3 on 2022-12-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_email',
            field=models.CharField(default='user@user.com', max_length=64),
        ),
    ]
