# Generated by Django 4.1.3 on 2022-12-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_useraccount_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='userAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('consignee_name', models.CharField(max_length=32)),
                ('consignee_phone', models.CharField(max_length=64)),
                ('default_flag', models.IntegerField(default=0)),
                ('province_name', models.CharField(max_length=32)),
                ('city_name', models.CharField(max_length=32)),
                ('region_name', models.CharField(max_length=32)),
                ('detail_address', models.CharField(max_length=64)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.useraccount')),
            ],
            options={
                'db_table': 'userAddress',
            },
        ),
    ]
