# Generated by Django 4.1.3 on 2022-12-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='area_code',
            field=models.IntegerField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
