# Generated by Django 4.1.3 on 2022-12-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_useraddress_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='area_code',
            field=models.IntegerField(),
        ),
    ]
