# Generated by Django 4.1.3 on 2022-12-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Category_name', models.CharField(max_length=100, null=True)),
                ('category_rank', models.IntegerField()),
                ('is_deleted', models.IntegerField()),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mall_category',
            },
        ),
    ]
