# Generated by Django 4.1.3 on 2022-11-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goodsinfo',
            table='mall_goodsinfo',
        ),
    ]
