# Generated by Django 4.1.3 on 2022-12-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_rename_goodsinfo_goods_alter_goods_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_promotion_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
