# Generated by Django 4.1.3 on 2022-12-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('goods', '0004_goods_goods_promotion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
