# Generated by Django 4.1.3 on 2022-11-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('grid_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('grid_url', models.CharField(max_length=100)),
                ('redirect_url', models.CharField(max_length=100)),
                ('grid_rank', models.IntegerField()),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mall_grid',
            },
        ),
    ]
