# Generated by Django 4.1.3 on 2022-11-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_banner_carousel_id_alter_grid_grid_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grid',
            name='grid_sort',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
