# Generated by Django 4.1.3 on 2022-12-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailinfo',
            name='sex',
            field=models.CharField(default='保密', max_length=16),
        ),
    ]
