# Generated by Django 4.1.3 on 2022-12-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_userdetailinfo_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailinfo',
            name='PRTS_num',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='userdetailinfo',
            name='furniture_num',
            field=models.IntegerField(default=500),
        ),
    ]
