# Generated by Django 4.1.3 on 2022-12-20 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0005_alter_goods_goods_category_id'),
        ('login', '0002_useraccount_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_cover_img', models.CharField(max_length=100, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('goods_count', models.IntegerField(default=0, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.useraccount')),
            ],
            options={
                'db_table': 'mall_cart',
            },
        ),
    ]
