# Generated by Django 4.1.3 on 2022-12-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0005_alter_goods_goods_category_id'),
        ('login', '0005_alter_useraddress_area_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='userOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pay_status', models.IntegerField()),
                ('pay_type', models.IntegerField()),
                ('pay_time', models.DateField()),
                ('order_status', models.IntegerField()),
                ('extra_info', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.IntegerField(default=0)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.useraccount')),
            ],
            options={
                'db_table': 'mall_order',
            },
        ),
        migrations.CreateModel(
            name='userOrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=100, null=True)),
                ('goods_cover_img', models.CharField(max_length=100, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('goods_count', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.userorder')),
            ],
            options={
                'db_table': 'mall_order_item',
            },
        ),
        migrations.CreateModel(
            name='userOrderAddress',
            fields=[
                ('order_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('user_phone', models.CharField(max_length=64)),
                ('province_name', models.CharField(max_length=32)),
                ('city_name', models.CharField(max_length=32)),
                ('region_name', models.CharField(max_length=32)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.userorder')),
            ],
            options={
                'db_table': 'mall_order_address',
            },
        ),
    ]
